#!/bin/sh

set -u # stop on unset variables
set -e # stop on error
set -x # echo commands

test -t 1 && USE_TTY="--tty" || true
docker run ${USE_TTY} -v $(pwd):/app/buildpack:ro heroku/buildpack-testrunner
